---
title: "BFP_R_code"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dplyr)
library(doParallel) 
library(quantmod) 
library(moments) 
library(rstan) 
library(xts)
library(lubridate)
library(ggplot2)
library(hrbrthemes)
library(shinystan)
library(corrplot)

#library(reshape2)
#launch_shinystan_demo()

```

```{r DATA upload and rv for SPX creation and formatting}
### DATA ###
setwd('/Users/AM/Documents/_CU Masters/2020 fall Bayesian_7393/Final_Project/data')

SP_500 = fread("^GSPC.csv")

VIX_9d_CBOE = fread("vix9ddailyprices.csv")
VIX_30d_CBOE = fread("vixcurrent.csv")
VIX_3m_CBOE = fread("vix3mdailyprices.csv")
VIX_6m_CBOE = fread("vix6mdailyprices.csv")

realized = fread("oxfordmanrealizedvolatilityindices 2.csv")

SP_500 = SP_500[,c("Date", "Close", "Volume")]
colnames(SP_500) = c("date", "close", "volume")
SP_500$date = as.Date(SP_500$date)
remove(SP_500)


vix_9d = VIX_9d_CBOE[-c(1,2,3,4), c("V1", "V5")]
colnames(vix_9d) = c("date", "vix_9d") 
vix_9d$date = as.Date(mdy(vix_9d$date))
vix_9d$vix_9d = as.numeric(vix_9d$vix_9d)
remove(VIX_9d_CBOE)

vix_30d = VIX_30d_CBOE[-c(1,2), c("V1", "V5")]
colnames(vix_30d) = c("date", "vix_30d") 
vix_30d$date = as.Date(mdy(vix_30d$date))
vix_30d$vix_30d = as.numeric(vix_30d$vix_30d)
remove(VIX_30d_CBOE)

vix_3m = VIX_3m_CBOE[-c(1,2,3), c("V1", "V5")]
colnames(vix_3m) = c("date", "vix_3m") 
vix_3m$date = as.Date(mdy(vix_3m$date))
vix_3m$vix_3m = as.numeric(vix_3m$vix_3m)
remove(VIX_3m_CBOE)

vix_6m = VIX_6m_CBOE[-c(1,2,3), c("V1", "V5")]
colnames(vix_6m) = c("date", "vix_6m") 
vix_6m$date = as.Date(mdy(vix_6m$date))
vix_6m$vix_6m = as.numeric(vix_6m$vix_6m)
remove(VIX_6m_CBOE)


temp = left_join(vix_9d, vix_30d, by = "date")
temp = left_join(temp, vix_3m, by = "date")
temp = left_join(temp, vix_6m, by = "date")
vix_df = temp
rm("vix_30d", "vix_3m", "vix_6m", "vix_9d", "temp")

realized$date = as_datetime(realized$V1)
realized = realized[,-c("V1")]
realized$date=realized$date+hours(2) #needed it as RV$V1 has 23:00 because of the daylight time (which wrongly shifts date to the previous one) 
realized$date = as.Date(realized$date)

temp = realized[realized$Symbol==".SPX",c("date", "close_price")]

#unique(realized$Symbol)
rv = realized[realized$Symbol==".SPX",]

### some examples of data upload and preprocessing
#VIXY = fread("^VIX.csv") # from Yahoo
#vix_cl=VIXY[,c("Date", "Close")]
#colnames(vix_cl) = c("date", "vix")
#vix_cl$date = as.Date(vix_cl$date)

#SP500_Y <- getSymbols( "^GSPC",
#src = "yahoo",
#from = "2015-01-01", to = "2020-11-12", auto.assign = FALSE
#)

```
http://www.cboe.com/products/vix-index-volatility/vix-options-and-futures/vix-index/vix-historical-data
https://www.cboe.com/index/dashboard/VIX6M#vix6m-overview

```{r #+#FUNC return functions }
##+++## add a normal return finction

## lin return ##
lin_ret = function (time_ser) { #the same as Delt(x, type = 'log') from Quantmod lib
  l_r = ROC(time_ser, type = "discrete")
  return(l_r)
}
# function check
lin_ret(c(10,15,18,27))

## log return ##

log_ret = function (time_ser) { #the same as Delt(x, type = 'log') from Quantmod lib
  log_time_ser = log(time_ser)
  l_ret = momentum(log_time_ser)
  return(l_ret)
}
# function check
log_ret(c(exp(1), exp(3), exp(4), exp(2), exp(5)))
log_ret(c(1,1.01,1.01^2))
Delt(c(exp(1), exp(3), exp(4), exp(2), exp(5)), type = 'log')
Delt(c(1,1.01,1.01^2))

``` 

```{r *#+# RV vs VIX build and visual inspection }
##++## plot together with VIX
##++## why VIX has NA? # solved (daylight time and 23:00 which resulted in  "date-1")
##+## (i.e. no visible prediction power in VIX, just repeats RV5 dynamic)

rv_vix = left_join(rv[,c("date", "rv5")], vix_df[,c("date", "vix_9d")], by = "date")
rv_vix_subset = rv_vix[((rv_vix$date>"2015-01-01") & (rv_vix$date<"2016-06-30")),]
coeff = max(rv_vix_subset$vix, na.rm = TRUE)/ max(rv_vix_subset$rv5, na.rm = TRUE)
ggplot(rv_vix_subset, aes(date)) + 
  geom_line(aes(y = rv5, colour = "rv5")) + 
  geom_line(aes(y = vix/ coeff, colour = "vix")) +
  scale_y_continuous(
    # Features of the first axis
    name = "Realized variance (5-min)",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="vix (same day)")) + 
  theme_ipsum() +
  theme(
    axis.title.y = element_text(color = "red", size=12),
    axis.title.y.right = element_text(color = "cyan3", size=12)) +
  ggtitle("some inference") 

```

```{r *#+# VIX returns added to rv_vix}
##+## plot rv vs vix_log_ret #found it USELESS
##+## double check that the dates of VIX and RV5 are really the same 
##+## (i.e. AGAIN no visible prediction power in VIX, just repeats RV5 dynamic)
rv_vix_subset$vix_log_ret = log_ret(rv_vix_subset$vix)
rv_vix_subset$vix_lin_ret = lin_ret(rv_vix_subset$vix)

coeff = 2*max(rv_vix_subset$vix_lin_ret, na.rm = TRUE)/ max(rv_vix_subset$rv5, na.rm = TRUE)
ggplot(rv_vix_subset, aes(date)) + 
  geom_line(aes(y = rv5, colour = "rv5"), alpha=.5) + 
  geom_line(aes(y = vix_lin_ret/ coeff, colour = "vix_log_ret"), alpha=.5) +
  scale_y_continuous(
    # Features of the first axis
    name = "realized variance (5-min)",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="vix_lin_ret (same day)")) + 
  theme_ipsum() +
  theme(
    axis.title.y = element_text(color = "red", size=12),
    axis.title.y.right = element_text(color = "cyan3", size=12)) +
  ggtitle("some inference") 

```

```{r *#+# PREPARE rv dataframe for plotting}
### plan
##++## find true S&P volatility caclulated 
##++## find true S&P volatility methodology
##-+-##   implement the methodology and compare results with the true ## let's trust the Oxford-Man institute
##++## explore the difference between estimator

rv_long <- melt(rv, id="date")
ggplot(data=rv_long, aes(x=date, y=value, colour=variable)) + 
  geom_line(alpha=.5) +
  theme_ipsum() +
  ylim(0,0.0007) +
  scale_x_date(limit=c(as.Date("2016-12-30"),as.Date("2017-11-10")))
remove(rv_long)

rv_subset = rv[((rv_vix$date>"2016-12-30") & (rv_vix$date<"2017-11-10")),] # just a plot
rv_subset_long <- melt(rv_subset, id="date")
ggplot(data=rv_subset_long, aes(x=date, y=value, colour=variable)) + 
  geom_line(alpha=.5) +
  theme_ipsum() 
remove(rv_subset)
remove(rv_subset_long)
```

```{r #...# STAN model GARCH(1,1)}
##++## analyze correlation RV and VIX for the same date #they almost repeat each other
##-+-## analyze correlation RV and VIX for the 30 days SHIFTED vix # no need imho, see the bullet above
##++## choose what to model (RV point or f(RV[interval])?) # return
##++## read papers about prediction of rv (Shepard and Shepard? etc)
#### add Rbsq
T <- length(rv_vix_subset$vix_lin_ret)-1
r <- rv_vix_subset$vix_lin_ret[-(c(1))]
sigma1 <- 0.1
T_out <- 10

stan_dat_garch11 = list(T=T, r = r, sigma1 = sigma1, T_out = T_out)
garch11 = "
data {
  int<lower=2> T; 
  real r[T];
  real<lower=0> sigma1;
  int<lower=0> T_out;
}
parameters {
  real mu; 
  real<lower=0> alpha0;          
  real<lower=0,upper=1> alpha1;  
  real<lower=0, upper=(1-alpha1)> beta1; 
}
transformed parameters {
  real<lower=0> sigma[T];
  sigma[1] = sigma1;
  for (t in 2:T)
    sigma[t] = sqrt(alpha0 + alpha1 * square(r[t - 1] - mu) + beta1  * square(sigma[t - 1]));
}
model {
  r ~ normal(mu,sigma);
}
generated quantities {
  real r_out[T_out];
  real sigma_out[T_out];
  sigma_out[1] = sqrt(alpha0 + alpha1 * square(r[T] - mu) + beta1 * square(sigma[T]));
  r_out[1] = normal_rng(mu, sigma_out[1]);
  for (i in 2:T_out) {
    sigma_out[i] = sqrt(alpha0 + alpha1 * square(r_out[i - 1] - mu) + beta1 * square(sigma_out[i - 1]));
    r_out[i] = normal_rng(mu, sigma_out[i]);
  }
}
"
r_fit = stan(model_code = garch11, data = stan_dat_garch11, iter = 10^4, chains = 3)
#summary(r_fit)$summary[,"Rhat"]
summary(r_fit)$summary[,c("mean", "50%","2.5%", "97.5%")][c("mu", "sigma[33]","r_out[1]", "alpha0", "alpha1", "beta1", "r_out[5]", "r_out[6]", "r_out[7]", "r_out[8]", "r_out[9]", "r_out[10]"),]

#alpha0=extract(y_fit, pars="alpha0")[[1]]
#sigma_out_2 = extract(y_fit, pars="sigma_out[2]")[[1]]
#str(sigma_out_2)
#summary(sigma_out_2)
#plot(density(sigma_out_2))
#sso <- launch_shinystan(r_fit)

```

```{r #...# STAN model realGARCH(1,1)}
#### add mu?
#### try different distribution (0,1) for x instead of N(0,1)
#### set up restrictions for the parameters (!!! see the paper)
#### set up priors (LNG paper aithors do use them)
##+++## increase tree depth
#### clear this chunk of any model implementation 
#### (making a typical separate chunks for any use of model; incl. forecasting model)
T <- length(rv_vix_subset$vix_lin_ret)-1
r <- rv_vix_subset$vix_lin_ret[-(c(1))]
x <- rv_vix_subset$rv5[-(c(1))]
sigma_r_1 <- 0.1 # it is sqrt(h[1])
T_out <- 5

stan_dat_real_garch = list(T = T, x = x, r = r, h_1 = (sigma_r_1)^2, T_out = T_out)
real_garch = "
data {
  int<lower=2> T;
  real<lower=0> x[T];
  real r[T];
  real<lower=0> h_1;
  //real<lower=0> sigma_u;
  int<lower=0> T_out;
}

parameters {
  real<lower=0.05> omega;          
  real<lower=0.2,upper=1>  beta;  
  real<lower=0.2, upper=0.7> gamma;   
  real xi;
  real phi;
  real tau_1;
  real tau_2;
  real<lower=0.000001> sigma_u;          
}

transformed parameters {
  real mu_x[T];
  real z[T]; 
  real<lower=0.000001> h[T];
  h[1] = h_1;  
  for (t in 2:T)
    h[t] = omega + beta * h[t - 1] + gamma  * x[t - 1];

  for (t in 1:T)
    z[t] = r[t] / sqrt(h[t]); 
    
  for (t in 1:T)
    mu_x[t] = xi + phi*h[t] + tau_1*z[t] + tau_2*(square(z[t]) - 1); 
}

model { 
  r ~ normal(0, sqrt(h));
  x ~ normal(mu_x, sigma_u);
}
generated quantities {
  real r_out[T_out];
  real<lower=0> h_out[T_out];
  real x_out[T_out];
  real z_out[T_out];
  real mu_x_out[T_out];
  
  h_out[1] = omega + beta * h[T] + gamma * x[T];
  r_out[1] = normal_rng(0, sqrt(h_out[1]));
  z_out[1] = r_out[1] / sqrt(h_out[1]);
  mu_x_out[1] = xi + phi*h_out[1] + tau_1*z_out[1] + tau_2*(square(z_out[1]) - 1);
  x_out[1] = normal_rng(mu_x_out[1], sigma_u);
  
  for (i in 2:T_out) {
    h_out[i] = omega + beta * h_out[i - 1] + gamma * x_out[i - 1];
    r_out[i] = normal_rng(0, sqrt(h_out[i]));
    z_out[i] = r_out[i] / sqrt(h_out[i]);
    mu_x_out[i] = xi + phi*h_out[i] + tau_1*z_out[i] + tau_2*(square(z_out[i]) - 1);
    x_out[i] = normal_rng(mu_x_out[i], sigma_u);
  }
}
"
r_fit = stan(model_code = real_garch, data = stan_dat_real_garch, iter = 3*10^3, chains = 3, 
             control = list(max_treedepth = 14))
summary(r_fit)$summary[,c("mean", "2.5%", "97.5%")][c("omega", "beta", "gamma", 
                                                      "xi", "phi", "tau_1", 
                                                      "tau_2", "sigma_u",
                                                      "h[10]", "h[20]", "h[100]", "h[200]",
                                                      "r_out[1]", "r_out[4]"),]

save(r_fit, file = "real_garch_test_3.rda", compress = "xz")

sso <- launch_shinystan(r_fit)
t = extract(r_fit)
plot(t$r_out[1])
```

```{r #+-+# SP_500/ VIX/ rv exploratory data analysis}
##+++## take vix(9/30/180/..), rv5_forward_lag(0/5/9/30...).. SPX_volat(9/30/...) as of vix_date+9/30/180
##---## add autocorrelation plot

SP_500_corr_df = inner_join(vix_df, rv[,c("date","rv5")], by = "date")
#colnames(SP_500_corr_df)[6] = "rv5"
# realized volatility rv5 today (i.e. as of (lead_0d)=0 days in the future from "date")
SP_500_corr_df$rv5_lead_9d = lead(SP_500_corr_df$rv5, 9)
SP_500_corr_df$rv5_lead_30d = lead(SP_500_corr_df$rv5, 30)
SP_500_corr_df$rv5_lead_3m = lead(SP_500_corr_df$rv5, 91)
SP_500_corr_df$rv5_lead_6m = lead(SP_500_corr_df$rv5, 182)

SP_500_corr_df = left_join(SP_500_corr_df, SP_500, by = "date")
SP_500_corr_df$volume = SP_500_corr_df$volume / 10^9
# historical volatility for the last (sd_nd) days as of "date" 
SP_500_corr_df$sd_9d = runSD(SP_500_corr_df$close, 9) 
SP_500_corr_df$sd_30d = runSD(SP_500_corr_df$close, 30)
SP_500_corr_df$sd_3m = runSD(SP_500_corr_df$close, 91)
SP_500_corr_df$sd_6m = runSD(SP_500_corr_df$close, 182)

# create temp columns with non leading na
SP_500_corr_df$temp_lead_9d = lead(SP_500_corr_df$close, 9) 
SP_500_corr_df$temp_lead_30d = lead(SP_500_corr_df$close,30)
SP_500_corr_df$temp_lead_3m = lead(SP_500_corr_df$close,91)
SP_500_corr_df$temp_lead_6m = lead(SP_500_corr_df$close,182)

SP_500_corr_df = SP_500_corr_df[SP_500_corr_df$date < "2020-01-01", ]

# historical volatility for the last (sd_nd) days as of "date"+ lead_9d (i.e. as of 9 days in the future from "date") 
SP_500_corr_df$sd_9d_lead_9d = runSD(SP_500_corr_df$temp_lead_9d, 9) 
SP_500_corr_df$sd_30d_lead_9d = runSD(SP_500_corr_df$temp_lead_9d, 30) 
SP_500_corr_df$sd_3m_lead_9d = runSD(SP_500_corr_df$temp_lead_9d, 91) 
SP_500_corr_df$sd_6m_lead_9d = runSD(SP_500_corr_df$temp_lead_9d, 182) 

# historical volatility for the last (sd_nd) days as of "date"+ lead_30d (i.e. as of 30 days in the future from "date")  
SP_500_corr_df$sd_9d_lead_30d = runSD(SP_500_corr_df$temp_lead_30d, 9) 
SP_500_corr_df$sd_30d_lead_30d = runSD(SP_500_corr_df$temp_lead_30d, 30) 
SP_500_corr_df$sd_3m_lead_30d = runSD(SP_500_corr_df$temp_lead_30d, 91) 
SP_500_corr_df$sd_6m_lead_30d = runSD(SP_500_corr_df$temp_lead_30d, 182) 

# historical volatility for the last (sd_nd) days as of "date"+ lead_3m (i.e. as of 91 days in the future from "date")  
SP_500_corr_df$sd_9d_lead_3m = runSD(SP_500_corr_df$temp_lead_3m, 9) 
SP_500_corr_df$sd_30d_lead_3m = runSD(SP_500_corr_df$temp_lead_3m, 30) 
SP_500_corr_df$sd_3m_lead_3m = runSD(SP_500_corr_df$temp_lead_3m, 91) 
SP_500_corr_df$sd_6m_lead_3m = runSD(SP_500_corr_df$temp_lead_3m, 182) 

# historical volatility for the last (sd_nd) days as of "date"+ lead_6m (i.e. as of 182 days in the future from "date")  
SP_500_corr_df$sd_9d_lead_6m = runSD(SP_500_corr_df$temp_lead_6m, 9) 
SP_500_corr_df$sd_30d_lead_6m = runSD(SP_500_corr_df$temp_lead_6m, 30) 
SP_500_corr_df$sd_3m_lead_6m = runSD(SP_500_corr_df$temp_lead_6m, 91) 
SP_500_corr_df$sd_6m_lead_6m = runSD(SP_500_corr_df$temp_lead_6m, 182) 

# remove temp columns 
SP_500_corr_df = SP_500_corr_df[,-c("temp_lead_9d", "temp_lead_30d", "temp_lead_3m", "temp_lead_6m")]

sum(is.na(SP_500_corr_df))

SP_500_corr_df = SP_500_corr_df[SP_500_corr_df$date > "2012-01-01", ]

M<-cor(SP_500_corr_df[,-c(1)])
corrplot(M)

### take-aways
# vix does not forecast a point estimate of RV
# vix has good positive correlation with interval volatility (especially 9 days)
# there is some correlation vix~volume to be explored
# there is some correlation vix_6m~close to be explored
# let's try to build the model around sd_9/30d_lead9/30d ~ vix9/30 

### code to double-check runSD
#temp = SP_500_corr_df$close[1:91]
#temp1 = 0
#for (i in (1:length(temp))){temp1 = temp1 + (temp[i]-mean(temp))^2}
#sqrt(temp1/(length(temp)-1))
```

```{r #+# plots sd_9/30d_lead9/30d ~ vix9/30}
##to_do### to analyze possible dependence of the current rv and future vix values
# basically this is exactly what the model does


subset = SP_500_corr_df[((SP_500_corr_df$date>"2019-01-30") & (SP_500_corr_df$date<"2019-08-30")),
                        c("date", "vix_9d", "vix_30d", "sd_9d","sd_9d_lead_9d", "sd_30d_lead_9d")] 

coeff = 4*max(subset$vix_9d)/ max(subset$sd_9d)
ggplot(subset, aes(date)) + 
  geom_line(aes(y = vix_9d, colour = "VIX_9d"), alpha = .6) + 
  geom_line(aes(y = sd_9d_lead_9d / coeff, colour = "sd_9d_lead_9d"), alpha = .3) +
  geom_line(aes(y = sd_9d/ coeff, colour = "sd_9d"), alpha = .6) +
  
  scale_y_continuous(
    # Features of the first axis
    name = "VIX_9d",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="SD")) + 
  theme_ipsum() +
  theme(
    axis.title.y = element_text(color = "blue", size=12),
    axis.title.y.right = element_text(color = "red", size=12)) +
  ggtitle("some inference") 

remove(subset)
### take-aways
# vix seems to be not forecasting/ leading even a point estimate of future RV
# but instead current SD and RV seems to be forecasting vix


```

```{r #...# realGarch prediction}
##---## find a metric to assess quality of prediction
##+## find a R library to do realGARCH
##---## build a loop
  # chose a time interval
  # build a model
  # compare the model prediction with the truth (9d after the end of the interval)
##---## compare results with results by the R rugarch library##
build_vix9_rv_subset = function(start_date, end_date) {
  rv_vix = left_join(rv[,c("date", "rv5")], vix_df[,c("date", "vix_9d")], by = "date")
  rv_vix_subset = rv_vix[((rv_vix$date>=start_date) & (rv_vix$date<=end_date)),]
  rv_vix_subset$vix_log_ret = log_ret(rv_vix_subset$vix_9d)
  rv_vix_subset$vix_lin_ret = lin_ret(rv_vix_subset$vix_9d)
  return(rv_vix_subset)
}

start_date = "2018-01-22"
subset_length = 7 # in months
step = 3 # in months
n_steps = 2 # 
T_out <- 5 # forecast depth, days

for (i in (0:n_steps)) {}
  subset = build_vix9_rv_subset(start_date, as.Date(start_date) + months(subset_length))
  T <- length(subset$vix_lin_ret)-1
  r <- rv_vix_subset$vix_lin_ret[-(c(1))]
  x <- rv_vix_subset$rv5[-(c(1))]
  sigma_r_1 <- 0.1 # it is sqrt(h[1])
  stan_dat_real_garch = list(T = T, x = x, r = r, h_1 = (sigma_r_1)^2, T_out = T_out)

```


```{r ##to do## run realGARCH for SPX_return~SPX_rv}
#### 
```

```{r ##to_do## parameters' stability check}
#### calculate parameters for 1...6 months time windows (neighboring, possibly overlapping)
```

future work
```{r other indexes return}
# to directly model SP500 return ~ rv, volume (not VIX as in the project)
# also try to model other indexes return
```

```{r ##to_do## similar research for other indexes}

```

```{r correlation vix~volume}
##to_do## there is some correlation vix~volume to be explored

```

```{r play with SPX (or other asset) volume}
##to_do## let's find a way to implement it into the model§
```

```{r correlation vix_6m~close}
##to_do## there is some correlation vix_6m~close to be explored

```

